name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --parallel

      - name: Run Brakeman
        run: bundle exec brakeman -q

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: chaiaurcode
          POSTGRES_PASSWORD: chaiaurcode
          POSTGRES_DB: battle_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgresql://chaiaurcode:chaiaurcode@localhost:5432/battle_test
      REDIS_URL: redis://localhost:6379/0

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Set up database
        run: bin/rails db:schema:load

      - name: Build Tailwind CSS
        run: bin/rails tailwindcss:build

      - name: Run tests
        run: bin/rails test
